//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.Objeto = new HashSet<Objeto>();
        }
    
        public int id_caja { get; set; }
        public string nombre { get; set; }
        public string modulo { get; set; }
        public string estante { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Objeto> Objeto { get; set; }
    }
}
